server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
test: 
  message: hello
management: 
  security: 
    enabled: false
management: 
  endpoints: 
    web: 
      exposure:
        include: *


spring:
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
